#pragma once
#include <windows.h>
#include <unordered_map>

const char* GetKeyName(int key) {
    static std::unordered_map<int, const char*> keyMap = {
        {VK_LBUTTON, "Left Mouse"},
        {VK_RBUTTON, "Right Mouse"},
        {VK_MBUTTON, "Middle Mouse"},
        {VK_XBUTTON1, "Mouse Button 4"},
        {VK_XBUTTON2, "Mouse Button 5"},
        {VK_BACK, "Backspace"},
        {VK_TAB, "Tab"},
        {VK_CLEAR, "Clear"},
        {VK_RETURN, "Enter"},
        {VK_SHIFT, "Shift"},
        {VK_LSHIFT, "Left Shift"},
        {VK_RSHIFT, "Right Shift"},
        {VK_CONTROL, "Ctrl"},
        {VK_LCONTROL, "Left Ctrl"},
        {VK_RCONTROL, "Right Ctrl"},
        {VK_MENU, "Alt"},
        {VK_LMENU, "Left Alt"},
        {VK_RMENU, "Right Alt"},
        {VK_PAUSE, "Pause"},
        {VK_CAPITAL, "Caps Lock"},
        {VK_ESCAPE, "Escape"},
        {VK_SPACE, "Space"},
        {VK_PRIOR, "Page Up"},
        {VK_NEXT, "Page Down"},
        {VK_END, "End"},
        {VK_HOME, "Home"},
        {VK_LEFT, "Left Arrow"},
        {VK_UP, "Up Arrow"},
        {VK_RIGHT, "Right Arrow"},
        {VK_DOWN, "Down Arrow"},
        {VK_SELECT, "Select"},
        {VK_PRINT, "Print"},
        {VK_EXECUTE, "Execute"},
        {VK_SNAPSHOT, "Print Screen"},
        {VK_INSERT, "Insert"},
        {VK_DELETE, "Delete"},
        {VK_HELP, "Help"},
        {VK_LWIN, "Left Windows"},
        {VK_RWIN, "Right Windows"},
        {VK_APPS, "Application"},
        {VK_SLEEP, "Sleep"},
        {VK_NUMPAD0, "Num 0"},
        {VK_NUMPAD1, "Num 1"},
        {VK_NUMPAD2, "Num 2"},
        {VK_NUMPAD3, "Num 3"},
        {VK_NUMPAD4, "Num 4"},
        {VK_NUMPAD5, "Num 5"},
        {VK_NUMPAD6, "Num 6"},
        {VK_NUMPAD7, "Num 7"},
        {VK_NUMPAD8, "Num 8"},
        {VK_NUMPAD9, "Num 9"},
        {VK_MULTIPLY, "Num *"},
        {VK_ADD, "Num +"},
        {VK_SEPARATOR, "Separator"},
        {VK_SUBTRACT, "Num -"},
        {VK_DECIMAL, "Num ."},
        {VK_DIVIDE, "Num /"},
        {VK_F1, "F1"},
        {VK_F2, "F2"},
        {VK_F3, "F3"},
        {VK_F4, "F4"},
        {VK_F5, "F5"},
        {VK_F6, "F6"},
        {VK_F7, "F7"},
        {VK_F8, "F8"},
        {VK_F9, "F9"},
        {VK_F10, "F10"},
        {VK_F11, "F11"},
        {VK_F12, "F12"},
        {VK_F13, "F13"},
        {VK_F14, "F14"},
        {VK_F15, "F15"},
        {VK_F16, "F16"},
        {VK_F17, "F17"},
        {VK_F18, "F18"},
        {VK_F19, "F19"},
        {VK_F20, "F20"},
        {VK_F21, "F21"},
        {VK_F22, "F22"},
        {VK_F23, "F23"},
        {VK_F24, "F24"},
        {VK_NUMLOCK, "Num Lock"},
        {VK_SCROLL, "Scroll Lock"},
        {VK_LSHIFT, "Left Shift"},
        {VK_RSHIFT, "Right Shift"},
        {VK_LCONTROL, "Left Ctrl"},
        {VK_RCONTROL, "Right Ctrl"},
        {VK_LMENU, "Left Alt"},
        {VK_RMENU, "Right Alt"},
        {VK_BROWSER_BACK, "Browser Back"},
        {VK_BROWSER_FORWARD, "Browser Forward"},
        {VK_BROWSER_REFRESH, "Browser Refresh"},
        {VK_BROWSER_STOP, "Browser Stop"},
        {VK_BROWSER_SEARCH, "Browser Search"},
        {VK_BROWSER_FAVORITES, "Browser Favorites"},
        {VK_BROWSER_HOME, "Browser Home"},
        {VK_VOLUME_MUTE, "Volume Mute"},
        {VK_VOLUME_DOWN, "Volume Down"},
        {VK_VOLUME_UP, "Volume Up"},
        {VK_MEDIA_NEXT_TRACK, "Next Track"},
        {VK_MEDIA_PREV_TRACK, "Previous Track"},
        {VK_MEDIA_STOP, "Media Stop"},
        {VK_MEDIA_PLAY_PAUSE, "Play/Pause"},
        {VK_LAUNCH_MAIL, "Mail"},
        {VK_LAUNCH_MEDIA_SELECT, "Media Select"},
        {VK_LAUNCH_APP1, "App 1"},
        {VK_LAUNCH_APP2, "App 2"},
        {VK_OEM_1, ";:"},
        {VK_OEM_PLUS, "+"},
        {VK_OEM_COMMA, ","},
        {VK_OEM_MINUS, "-"},
        {VK_OEM_PERIOD, "."},
        {VK_OEM_2, "/?"},
        {VK_OEM_3, "`~"},
        {VK_OEM_4, "[{"},
        {VK_OEM_5, "\\|"},
        {VK_OEM_6, "]}"},
        {VK_OEM_7, "'\""},
        {VK_OEM_8, "OEM 8"},
        {VK_OEM_102, "OEM 102"},
        {VK_PROCESSKEY, "Process"},
        {VK_ATTN, "Attn"},
        {VK_CRSEL, "CrSel"},
        {VK_EXSEL, "ExSel"},
        {VK_EREOF, "Erase EOF"},
        {VK_PLAY, "Play"},
        {VK_ZOOM, "Zoom"},
        {VK_NONAME, "No Name"},
        {VK_PA1, "PA1"},
        {VK_OEM_CLEAR, "Clear"}
    };
    auto it = keyMap.find(key);
    if (it != keyMap.end()) {
        return it->second;
    }
    static char keyName[64];
    if ((key >= '0' && key <= '9') || (key >= 'A' && key <= 'Z')) {
        snprintf(keyName, sizeof(keyName), "%c", key);
        return keyName;
    }
    return "Unknown Key";
}
